filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/postgresql/*.log
  document_type: postgresql
  json.message_key: log


filebeat.modules:
- module: system


output.logstash:
  hosts: ["localhost:5044"]
  username: "{{ elastic_user }}"
  password: "{{ elastic_password }}"
