filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/postgresql/*.log
  document_type: postgresql
  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after


output.logstash:
  hosts: ["localhost:5044"]
  username: "{{ elastic_user }}"
  password: "{{ elastic_password }}"
